### ISSUE TITLE
Compare function returns 'true' when tested arrays length is not equal

### ISSUE THREAD

**Issue by psxcode** [GaneshSPatil/chai-arrays#1]
assertArrays.js @ 13
`const compare = function(actual, expected) {     
  return actual.every((value, index) => value === expected[index]);
};`

`compare([], [1, 2, 3]); // true` 
`compare([1, 2], [1, 2, 3]); // true`

**Comment by GaneshSPatil** [comment]
@psxcode -- thanks for reporting the issue.
I have published `v1.1.0` which contains the fix for the current issue.
can you please verify?

Thanks

**Comment by psxcode** [comment]
Great.
I think that did it.
It works now.

**Comment by GaneshSPatil** [comment]
@psxcode -- Thanks
