### ISSUE TITLE
Support for typed arrays?

### ISSUE THREAD

**Issue by mattbishop** [GaneshSPatil/chai-arrays#3]
Can this be used with typed arrays like Uint8Array?

**Comment by GaneshSPatil** [comment]
@mattbishop -- `Uint8Array`(or any other unsigned integer array) is not supported by the `chai-arrays` plugin, until now.

Thanks for letting us know. We will add support for it in the next release!

**Comment by mattbishop** [comment]
Thanks! There's a bunch of them: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays

**Comment by GaneshSPatil** [comment]
@mattbishop -- I have added support for Unsigned integer array in [chai-arrays v2.0.0](https://www.npmjs.com/package/chai-arrays), can you take a look make sure the issue has been sorted?

Release `2.0.0` Supports:
* `Array`
* `Uint8Array`
* `Unit16Array`
* `Unit32Array`
* `Uint8ClampedArray`

Thanks in advance!

**Comment by GaneshSPatil** [comment]
Also, @mattbishop -- API calls for the unsigned integer arrays are same as of normal array in JS, expect the type check
Please refer : https://github.com/GaneshSPatil/chai-arrays#array

**Comment by mattbishop** [comment]
Thanks, this is an improvement!
What do you think about an ease-of-use change to allow for var-arg testing of contained values across the board? something like `expect(new Uint8Array([1, 2, 3])).to.be.equalTo(1, 2, 3);`

so the expected values are a value list. For the most part the type of the array (Uint8Array) is not as critical as the contents.

**Comment by GaneshSPatil** [comment]
@mattbishop -- thanks for the suggestion!
most of the people still would like to have the current equality API, as the sometimes we need to use the defined  `expected` and `actual`.

Though, I see the convenience in  `var-arg` style `containingAllOf` and `containingAnyOf`.

I will spend some more time and will get back to you on this.

Thanks!

**Comment by GaneshSPatil** [comment]
@mattbishop -- spent some time looking into the use case, as it is breaking change and just providing a syntactic sugar, need more interest from the users, for this proposal.
