### ISSUE TITLE
Doesn't support ranges

### ISSUE THREAD

**Issue by invisiblegaudi** [GaneshSPatil/chai-arrays#4]
Would be nice to add support for ranges (I can contribute)

**Comment by GaneshSPatil** [comment]
@invisiblegaudi -- Extremely sorry for the delayed response. I was vacationing :)
would you be able to provide the usage example of ranges? How would the API look for ranges?

Once we are in the agreement on the intended usage of the ranges API, we(you?) can contribute to this feature!

**Comment by GaneshSPatil** [comment]
Closing as stale..
